importScripts("./version.js");

// Refresh installed clients for recurring quest-state reconciliation.
// Generated by scripts/bump_build.py; do not edit release values manually.
const GENERATED_WORKER_VERSION = "081204";
const WORKER_VERSION = self.SUMMER_QUEST_BUILD?.version || "unknown";
if (
  !self.SUMMER_QUEST_BUILD?.isValid?.(WORKER_VERSION) ||
  WORKER_VERSION !== GENERATED_WORKER_VERSION
) {
  throw new Error(`[PWA] Invalid or mismatched MMDDNN worker version: ${WORKER_VERSION}`);
}
const CACHE_PREFIX = "summer-quest-app-";
const CACHE_NAME = "summer-quest-app-081204";
const APP_SCOPE_PATH = new URL("./", self.location.href).pathname;
const APP_INDEX_PATH = new URL("./index.html", self.location.href).pathname;
const PREVIOUS_ACTIVE_WORKER_URL = self.registration.active?.scriptURL || null;
const APP_SHELL_URLS = [
  "./index.html",
  "./style.css",
  "./manifest.json",
  "./version.js",
  "./data/iconFonts.js",
  "./data/pwa.js",
  "./data/quests.js",
  "./data/boardConfig.js",
  "./data/mediaStorage.js",
  "./data/finale.js",
  "./data/analytics.js",
  "./data/app.js",
  "./data/survey.js",
  "./data/journal.js",
  "./assets/vendor/cropperjs/cropper.min.css",
  "./assets/vendor/cropperjs/cropper.min.js",
  "./assets/fonts/Montserrat-Variable.woff2",
  "./assets/fonts/LibreBaskerville-Variable.woff2",
  "./assets/fonts/LibreBaskerville-Italic-Variable.woff2",
  "./assets/fonts/Caveat-Variable.woff2",
  "./assets/fonts/MaterialSymbolsOutlined.woff2",
  "./assets/fonts/MaterialSymbolsRounded.woff2",
  "./assets/favicon/favicon.ico",
  "./assets/favicon/favicon-16x16.png",
  "./assets/favicon/favicon-32x32.png",
  "./assets/favicon/apple-touch-icon.png",
  "./assets/favicon/icon-192.png",
  "./assets/favicon/icon-512.png",
  "./assets/hero-park-clean.png",
  "./assets/hero-summer-journal.png",
  "./assets/illustrations/icons/old/judgmental-pigeon.png",
  "./assets/link-preview.jpg",
  "./assets/home-screen-help/iphone-step-1.png",
  "./assets/home-screen-help/iphone-step-2.png",
  "./assets/home-screen-help/iphone-step-3.png",
  "./assets/home-screen-help/android-step-1.png",
  "./assets/home-screen-help/android-step-2.png",
  "./assets/home-screen-help/android-step-3.png",
  "./assets/illustrations/icon.png",
  "./assets/illustrations/overlays/completed-stamp-256.png",
  "./assets/illustrations/icons/animal-statue.png",
  "./assets/illustrations/icons/birthday-selfie.png",
  "./assets/illustrations/icons/bodega-cat.png",
  "./assets/illustrations/icons/celebrate-together.png",
  "./assets/illustrations/icons/cinema-moment.png",
  "./assets/illustrations/icons/city-freebies.png",
  "./assets/illustrations/icons/diy-craft.png",
  "./assets/illustrations/icons/favorite-art.png",
  "./assets/illustrations/icons/get-sweaty.png",
  "./assets/illustrations/icons/golden-hour.png",
  "./assets/illustrations/icons/hidden-gems.png",
  "./assets/illustrations/icons/human-pyramid.png",
  "./assets/illustrations/icons/live-events.png",
  "./assets/illustrations/icons/ny-eats.png",
  "./assets/illustrations/icons/nyc-spirit.png",
  "./assets/illustrations/icons/off-the-map.png",
  "./assets/illustrations/icons/open-market.png",
  "./assets/illustrations/icons/park-picnic.png",
  "./assets/illustrations/icons/pup-arazzi.png",
  "./assets/illustrations/icons/random-kindness.png",
  "./assets/illustrations/icons/showtime.png",
  "./assets/illustrations/icons/street-fashion.png",
  "./assets/illustrations/icons/street-mural.png",
  "./assets/illustrations/icons/subway-romance.png",
  "./assets/illustrations/icons/time-capsule.png",
  "./assets/illustrations/icons/waterfront-wonders.png"
];

async function fetchFresh(request) {
  return fetch(request, { cache: "no-store" });
}

async function cacheAppShell() {
  const cache = await caches.open(CACHE_NAME);

  await Promise.all(APP_SHELL_URLS.map(async url => {
    const request = new Request(url, { cache: "reload" });
    const response = await fetch(request);

    if (!response.ok) {
      throw new Error(`Unable to cache ${url}: ${response.status}`);
    }

    await cache.put(url, response);
  }));
}

async function deleteObsoleteAppCaches() {
  const cacheNames = await caches.keys();
  const obsoleteNames = cacheNames.filter(
    name => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME
  );

  await Promise.all(obsoleteNames.map(name => caches.delete(name)));
}

function shouldRefreshExistingAppClients() {
  if (!PREVIOUS_ACTIVE_WORKER_URL) return false;

  try {
    return new URL(PREVIOUS_ACTIVE_WORKER_URL).searchParams.get("v") !== WORKER_VERSION;
  } catch {
    // An unversioned legacy worker is still an older shell candidate.
    return true;
  }
}

function isAppShellClient(client) {
  const url = new URL(client.url);
  return url.origin === self.location.origin &&
    (url.pathname === APP_SCOPE_PATH || url.pathname === APP_INDEX_PATH);
}

async function cachedFallback(request, fallbackUrl) {
  const cache = await caches.open(CACHE_NAME);
  const directMatch = await cache.match(request, { ignoreSearch: true });

  if (directMatch) return directMatch;
  if (fallbackUrl) return cache.match(fallbackUrl, { ignoreSearch: true });
  return null;
}

async function cacheFirst(request, fallbackUrl) {
  const cached = await cachedFallback(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok && response.type === "basic") {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const fallback = await cachedFallback(request, fallbackUrl);
    if (fallback) return fallback;
    return new Response("", {
      status: 503,
      statusText: "Offline"
    });
  }
}

async function appShellNavigation(request) {
  const cache = await caches.open(CACHE_NAME);
  const cachedShell = await cache.match("./index.html", { ignoreSearch: true });
  if (cachedShell) return cachedShell;

  try {
    return await fetchFresh(request);
  } catch {
    return new Response("", {
      status: 503,
      statusText: "Offline"
    });
  }
}

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    // The shell is complete before this worker takes control.  Leaving a
    // downloaded worker in `waiting` indefinitely is not reliable for an
    // iOS Home Screen app: closing its window does not necessarily terminate
    // the controlled client.  Activating here lets an already-installed app
    // advance on its next controlled navigation without touching user data.
    await cacheAppShell();
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    await deleteObsoleteAppCaches();
    const clients = await self.clients.matchAll({ type: "window" });
    const appShellClients = shouldRefreshExistingAppClients()
      ? clients.filter(isAppShellClient)
      : [];

    // Older installed shells do not contain the controllerchange reload logic
    // added in later builds. Tell current shells not to race this navigation,
    // then navigate only real app-shell windows onto the cache just installed.
    appShellClients.forEach(client => {
      client.postMessage({
        type: "SUMMER_QUEST_SW_ACTIVATED",
        version: WORKER_VERSION,
        reloadRequested: true
      });
    });

    await self.clients.claim();
    clients.forEach(client => {
      if (appShellClients.includes(client)) return;
      client.postMessage({
        type: "SUMMER_QUEST_SW_ACTIVATED",
        version: WORKER_VERSION
      });
    });

    await Promise.all(appShellClients.map(async client => {
      try {
        await client.navigate(client.url);
      } catch {
        // The page-level controllerchange fallback still reloads current
        // shells when navigation is unavailable or interrupted.
      }
    }));
  })());
});

self.addEventListener("message", event => {
  if (event.data?.type === "SUMMER_QUEST_SKIP_WAITING") {
    event.waitUntil(self.skipWaiting());
    return;
  }

  if (event.data?.type === "SUMMER_QUEST_GET_VERSION") {
    const message = {
      type: "SUMMER_QUEST_SW_VERSION",
      version: WORKER_VERSION
    };
    if (event.ports?.[0]) event.ports[0].postMessage(message);
    else event.source?.postMessage(message);
  }
});

self.addEventListener("fetch", event => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Validation pages request current source explicitly; do not let an installed
  // app cache turn their cache-busting URLs into stale test inputs.
  if (request.cache === "no-store") {
    event.respondWith(fetchFresh(request));
    return;
  }

  const isAppShellNavigation =
    request.mode === "navigate" &&
    (url.pathname === APP_SCOPE_PATH || url.pathname === APP_INDEX_PATH);

  if (isAppShellNavigation) {
    event.respondWith(appShellNavigation(request));
    return;
  }

  event.respondWith(cacheFirst(request));
});
